spring:
  application:
    name: pyksel
  datasource:
    url: jdbc:postgresql://localhost:5432/pyksel
    username: pyksel
    password: pyksel
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:default-secret-for-local-extra-long-even-longer}
    expiration-ms: 86400000